#!/bin/bash 

celery -A messenger_project.messenger_project worker -l info &
celery -A messenger_project.messenger_project beat -l info &
daphne -b 0.0.0.0 -p 8000 messenger_project.messenger_project.asgi:application

wait